// <auto-generated />
using System;
using EEEEReader.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EEEEReader.Data.Migrations
{
    [DbContext(typeof(EEEEReaderDbContext))]
    partial class EEEEReaderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("EEEEReader.Data.Models.Librairie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Librairie");
                });

            modelBuilder.Entity("EEEEReader.Data.Models.Livre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auteur")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CoverRaw")
                        .HasColumnType("BLOB");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Langue")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LibrairieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pourcentage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resume")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibrairieId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Livres");
                });

            modelBuilder.Entity("EEEEReader.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibrairieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibrairieId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("EEEEReader.Data.Models.Livre", b =>
                {
                    b.HasOne("EEEEReader.Data.Models.Librairie", null)
                        .WithMany("Livres")
                        .HasForeignKey("LibrairieId");

                    b.HasOne("EEEEReader.Models.Utilisateur", null)
                        .WithMany("LivresRecent")
                        .HasForeignKey("UtilisateurId");
                });

            modelBuilder.Entity("EEEEReader.Models.Utilisateur", b =>
                {
                    b.HasOne("EEEEReader.Data.Models.Librairie", "Librairie")
                        .WithMany()
                        .HasForeignKey("LibrairieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Librairie");
                });

            modelBuilder.Entity("EEEEReader.Data.Models.Librairie", b =>
                {
                    b.Navigation("Livres");
                });

            modelBuilder.Entity("EEEEReader.Models.Utilisateur", b =>
                {
                    b.Navigation("LivresRecent");
                });
#pragma warning restore 612, 618
        }
    }
}
